#GitHub Action for CICD pipeline
name: java-maven-sonar-argocd-gh_actions-k8s CICD

on:
  # Triggers the workflow on push on the "main" branch
  workflow_dispatch:
jobs:

  Checkout-Build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout and Build
        uses: actions/checkout@v3

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run the Maven package
        run: |
         cd spring-boot-app
         mvn package --file pom.xml
         mkdir staging
         cp target/*.jar staging
      - name: Sonarqube scan
        env:
         SONARQUBE_HOST: ${{ secret.SONARQUBE_HOST }}
         SONARQUBE_SECRET: ${{ secret.SONARQUBE_SECRET }}
        run: |
         cd /home/runner/work/java-maven-sonar-argocd-gh_actions-k8s/java-maven-sonar-argocd-gh_actions-k8s/spring-boot-app
         mvn sonar:sonar -Dsonar.login="$SONAR_SECRET" -Dsonar.host.url="$SONAR_HOST"
          
      - uses: actions/upload-artifact@v4
        with:
          name: spring-boot-web
          path: /home/runner/work/java-maven-sonar-argocd-gh_actions-k8s/java-maven-sonar-argocd-gh_actions-k8s/spring-boot-app/staging/spring-boot-web.jar
