#GitHub Action for CICD pipeline
name: java-maven-sonar-argocd-gh_actions-k8s CICD

on:
  # Triggers the workflow on push on the "main" branch
  push:
    branches: [ "dev" ]
  workflow_dispatch:
jobs:

  Checkout-Build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout and Build
        uses: actions/checkout@v3

        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run the Maven package
      - run: mvn package --file spring-boot-app/pom.xml
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
         name: Package
         path: staging
 
