#GitHub Action for CICD pipeline
name: java-maven-sonar-argocd-gh_actions-k8s CICD

on:
  push:
    branches:
      [ yashtank/dev ]
  workflow_dispatch:
    
      
jobs:

  Checkout-Build-Push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Push Image Tag number to repo
        run: |
          pwd
          ls
          


        
