
#GitHub Action for CICD pipeline
name: java-maven-sonar-argocd-gh_actions-k8s CICD

on:
  push:
    branches:
      [ dev ]
  
  # Triggers the workflow on push on the "main" branch
  workflow_dispatch:
jobs:

  Checkout-Build:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout and Build
        uses: actions/checkout@v3
      - name: Set Docker Image Tag
        working-directory: /home/runner/work/java-maven-sonar-argocd-gh_actions-k8s/java-maven-sonar-argocd-gh_actions-k8s/spring-boot-app-manifests
        run: |
          IMAGE_TAG=$(date +'%y-%m-%d-%s')
          sed -i "s/ultimate-cicd:.*/ultimate-cicd:$IMAGE_TAG/g" deployment.yml
          cat deployment.yml
